export const OPEN_CARTITEM = 'OPEN_CARTITEM'
export const CLOSE_CARTITEM = 'CLOSE_CARTITEM'
export const OPEN_FORM_SIGNUP = 'OPEN_FORM_SIGNUP'
export const OPEN_FORM_SIGNIN = 'OPEN_FORM_SIGNIN'
export const READ_MORE = "READ_MORE"
export const OVERFLOW_HIDDEN = "OVERFLOW_HIDDEN"